# Change these first
owner: 1QLabs # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: 1QLabs Website
    url: https://www.1qlabs.ai
  - name: Talking Brands Website
    url: https://www.talkingbrands.ai
  - name: Talking Brands App
    url: https://app.talkingbrands.ai
  - name: Adaptive Educational Intelligence (AEI) Website
    url: https://www.thelearning.ai
  - name: Adaptive Educational Intelligence (AEI) App
    url: https://app.thelearning.ai

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.1qlabs.ai
  # baseUrl: /your-repo-name
  logoUrl: https://uploads-ssl.webflow.com/64bde329a7cb1c7fd4341fe4/64bde4dab40e27828da7a17d_1qlabs-logo.svg
  name: Upptime
  introTitle: "**1QLabs Status** is the dedicated status monitor for our services."
  introMessage: This status page reflects **real-time** updates directly from our internal systems, ensuring transparency without the need for a dedicated server setup.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
